// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW3J3lxXbRqZHNKRRdCjm9giAB93vajP4',
    appId: '1:794051623275:web:663f7e6dc87f0a6d00342e',
    messagingSenderId: '794051623275',
    projectId: 'foodie-app-5c80f',
    authDomain: 'foodie-app-5c80f.firebaseapp.com',
    storageBucket: 'foodie-app-5c80f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAEbmJv-2Xj-6llvAzp9WpnqQwUMLcEaE',
    appId: '1:794051623275:android:220c196c537b046b00342e',
    messagingSenderId: '794051623275',
    projectId: 'foodie-app-5c80f',
    storageBucket: 'foodie-app-5c80f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9d-g4qI_uFVqK80E4tpNgY3p2W-gzXm8',
    appId: '1:794051623275:ios:1e6a5eacec7dc7ef00342e',
    messagingSenderId: '794051623275',
    projectId: 'foodie-app-5c80f',
    storageBucket: 'foodie-app-5c80f.appspot.com',
    iosBundleId: 'com.example.foodieapp',
  );
}
